### PR TITLE
Add a tutorial step on testing

### PR DESCRIPTION
**Pull request by freakboy3742**
Builds on #176.

Briefcase 0.3.12 will include `--test` options; add a tutorial on how to use that option.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by mhsmith — APPROVED** [review]
The changes all look fine. But if we merge them now, they'll go live on https://docs.beeware.org/, despite the fact that the testing feature hasn't been released yet.

In fact, this problem has already happened on https://briefcase.readthedocs.io/. The root URL redirects to https://briefcase.readthedocs.io/en/latest/, which is built from the development branch, and therefore includes all the unreleased `--test` options. This is also the version which shows up on Google when you search for things like "briefcase run".

Instead, the default version should be https://briefcase.readthedocs.io/en/stable/, and docs.beeware.org should follow the same pattern.

**Comment by mhsmith** [comment]
Also FYI: it doesn't look as if merging #176 has automatically changed the target branch of this PR, though it can be changed manually by clicking the Edit button.

**Comment by freakboy3742** [comment]
> Also FYI: it doesn't look as if merging #176 has automatically changed the target branch of this PR, though it can be changed manually by clicking the Edit button.

Turns out the trigger is deleting the PR's branch, not the merge itself. I habitually delete branches as soon as I merge, so I didn't catch that it's the delete that actually does the update on the second PR.

**Comment by freakboy3742** [comment]
> Instead, the default version should be https://briefcase.readthedocs.io/en/stable/, and docs.beeware.org should follow the same pattern.

I've modified the RTD configuration to do this for Briefcase.

This tutorial is a little more complicated because we essentially don't cut "BeeWare" releases. There is a 0.3 branch, but it hasn't been updated since the original release of Briefcase 0.3.0. 

Having the the tutorial on latest rather than stable means we can make immediate updates and improvements to the text, rather than needing to go through a release cycle to get a tutorial tweak live. Updates that clarify language or tweak installation instructions are much more common on the tutorial than an entirely new tutorial step (or a version incompatible tutorial step, as we're seeing here). On that basis, I'm not sure it's worth moving the tutorial to a "stable" branch.

**Comment by mhsmith** [comment]
OK, in that case, I'll mark this PR as a draft to indicate it shouldn't be merged until after the next Briefcase release.

**Pull request merged**
