### PR TITLE
Use toga.InfoDialog() instead of info_dialog()

### LINKED ISSUE #447: info_dialog() has been deprecated
### Describe the bug

With toga [0.4.6](https://github.com/beeware/toga/releases/tag/v0.4.6), there's a warning that `info_dialog()` is deprecated.

Tutorial needs to be updated use `toga.InfoDialog()`.

### Steps to reproduce

1. Run steps on tutorial 4 onwards.
2. Warning is on the console.

### Expected behavior

No deprecation warnings on the tutorial.

### Screenshots

_No response_

### Environment

- Operating System: macOS
- Python version: 3.13.0
- Software versions:
  - Briefcase: 0.3.20
  - Toga: (toga-cocoa==0.4.8, toga-core==0.4.8)

### Logs

```
/Users/kesara/lab/beeware-tutorial/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/app_packages/toga/window.py:537: DeprecationWarning: info_dialog(...) has been deprecated; use dialog(toga.InfoDialog(...))
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kesara**
With toga [0.4.6](https://github.com/beeware/toga/releases/tag/v0.4.6), `info_dialog()` has been deprecated.
This addresses `async` part of the main tutorial.
Fixes #447

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by kesara** [comment]
8a024b8c0510963ef4b2fb0b1f632a92a23b7548 fixes the warning for Camera access tutorial.

**Review by freakboy3742 — APPROVED** [review]
Fantastic - thanks for the fix!

**Comment by kesara** [comment]
2f2bb6bd9517caf5600fc2942496d1475b2032d2 introduces `async` and `await` early on in Tutorial 4 with a promise that Tutorial 8 will discuss that in more detail.

**Review by freakboy3742 — APPROVED** [review]
One small edit to the async explainer, but otherwise this looks great! Thanks.

**Pull request merged**
