### PR TITLE
Add copy button for code blocks

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- Adds `sphinx-copybutton` to add a copy button to code blocks

As seen on right:
image

- For commands in the terminal, updated uses of `.. code-block:: bash` with `.. code-block:: console` since the former is for literal bash scripts, not terminal sessions.
- Updated all Windows `CMD` prompts to match `(beeware-venv) C:\...>`
- Ran through the tutorial on each platform to ensure the terminal commands and output match current Briefcase behavior.

## Notes
meta: there aren't any PR merge requirements for this repo

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
huh....using the docs [preview on RTD](https://beeware--210.org.readthedocs.build/en/210/tutorial/tutorial-1.html), clicking the copy button copies the entire block including the `$PS1`. However, on my local build, it does not...

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
I like this idea a lot - but including the prompt/preamble is a bit of a dealbreaker for me.

FWIW - I'm also the prompt copied in *both* local builds and RTD builds.

**Comment by rmartin16** [comment]
Agreed; it's more frustrating than copying the command yourself.

I'll try to get to the bottom of it. If I do, I'll also separate out the instances where the command output is included.

**Comment by rmartin16** [comment]
Saw this today in another repo's dependabot....promising...

> Bumps [sphinx-copybutton](https://github.com/executablebooks/sphinx-copybutton) from 0.5.1 to 0.5.2.
> 
> Release notes
> _Sourced from [sphinx-copybutton's releases](https://github.com/executablebooks/sphinx-copybutton/releases)._
> 
> > ## v0.5.2 - 2022-11-15
> > ([full changelog](https://github.com/executablebooks/sphinx-copybutton/compare/v0.5.1...v0.5.2))
> > 
> > * BUG: Don't exclude `.gp` class by default.  This made excluding prompts more automatic, but broke the existing pattern-based prompt exclusion.  [#188](https://redirect.github.com/executablebooks/sphinx-copybutton/pull/188) ([`@​rkdarst`](https://github.com/rkdarst))
> > * MAINT: Add Sphinx Extension classifier ([#189](https://redirect.github.com/executablebooks/sphinx-copybutton/issues/189))  [#189](https://redirect.github.com/executablebooks/sphinx-copybutton/pull/189) ([`@​jdillard`](https://github.com/jdillard))
> > * DOCS: Improve docs related to text exclusion [#187](https://redirect.github.com/executablebooks/sphinx-copybutton/pull/187) ([`@​rkdarst`](https://github.com/rkdarst))

**Comment by rmartin16** [comment]
ahh...so that's why prompt exclusion worked locally; I was using 0.5.1 while RTD installed 0.5.2....and prompt exclusion doesn't seem to be working too well in 0.5.2.

Nonetheless, they have a lot of [docs](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#automatic-exclusion-of-prompts-from-the-copies) about prompt exclusion.....something here gotta make this work.

**Comment by rmartin16** [comment]
https://beeware--210.org.readthedocs.build/en/210/tutorial/tutorial-1.html

All right; I updated the `copybutton` config to exclude text from the copy in code blocks if identified by `Pygments` as a line number (`.linenos`), generic prompt (`.gp`), or generic output (`.go`).

So, now, the copy button works very similarly to how Sphinx is already making the prompt "unselectable" when you try to copy the code block yourself. (The exception being that Sphinx doesn't exclude the command output included the code block).

This is still a bit wonky, though...
1) If the prompt contains a space, `Pygments` doesn't include the space in the `span` defining the prompt...so it gets included the copy (whether from the button or manually).
2) When the code block contains command output, the copy button includes a lot of newlines in the copied text.

Getting closer.

**Comment by rmartin16** [comment]
> 2. When the code block contains command output, the copy button includes a lot of newlines in the copied text.

Finally dawned on me that `Pygments` is treating `...` as a prompt because it is the Python REPL line continuation prompt. So, a code block like this seemingly contains a bunch of "empty commands" which adds a bunch of newlines to the copy.

```
    .. code-block:: doscon

      (beeware-venv)C:\...>briefcase run web

      [helloworld] Generating application template...
      ...
      [helloworld] Created build\helloworld\web\static

      [helloworld] Building web project...
      ...
      [helloworld] Built build\helloworld\web\static\www\index.html
```

So, here is a more custom approach:
```python
# -- Options for copy button ---------------------------------------------------

copybutton_prompt_text = "|".join(
    [
        # Python REPL
        # r">>>\s?",
        # Python REPL line continuation
        # r"\.\.\.\s?",
        # IPython
        # r"In \[\d*\]:\s?",
        # Jupyter
        # r" {5,8}:\s?",
        # IPython and Jupyter line continuation
        # r" {2,5}\.\.\.:\s?",
        # non-Windows terminal session
        r"\$\s?",
        # non-Windows terminal session in venv
        r"\(beeware-venv\) \$\s?",
        # Windows terminal session
        r"C:\\>\s?",
        r"C:\\\.\.\.>\s?",
        # Windows terminal session in venv
        r"\(beeware-venv\) C:\\>\s?",
        r"\(beeware-venv\) C:\\\.\.\.>\s?",
    ]
)
copybutton_prompt_is_regexp = True
copybutton_remove_prompts = True
copybutton_only_copy_prompt_lines = True
copybutton_copy_empty_lines = False
```

I've added `\s?` to the end of all of them to allow for including a space or not after the prompt. Most shells put a space here; although, `cmd` does not. And the existing docs are not consistent in this. So, while they can be fixed...this affords some flexibility for those missed. (The same is true of the space after `(beeware-venv)`.)

**Comment by rmartin16** [comment]
@freakboy3742, please let me know your thoughts on these options.

We can stick to the decisions about what `Pygments` is marking as prompt and accept the occasional spaces and newlines with `copybutton`...or pursue the more custom configuration.

**Review by freakboy3742 — COMMENTED** [review]
The regex itself makes sense to me (at least to the extent that regexes ever do); the only part that gives me pause is the introduction of the extra spaces into the windows prompts. The "spaceless" version was attempting to reproduce what a user will see in practice. Are the spaces you've added here purely cosmetic, or needed to support the regex?

**Comment by rmartin16** [comment]
Oh, that's fair; there was a fix of space and no space in the docs already. I'll go the other way with no space.

**Comment by rmartin16** [comment]
Actually, for me there is a space between the `(venv)` and the current directory....are you seeing something else?

```
Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>cd github\beeware\briefcase

C:\Users\user\github\beeware\briefcase>venv-3.11-winstore-briefcase\Scripts\activate.bat

(venv-3.11-winstore-briefcase) C:\Users\user\github\beeware\briefcase>
```

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\user> cd .\github\beeware\briefcase\
PS C:\Users\user\github\beeware\briefcase> .\venv-3.11-winstore-briefcase\Scripts\Activate.ps1
(venv-3.11-winstore-briefcase) PS C:\Users\user\github\beeware\briefcase>
```

**Comment by freakboy3742** [comment]
Unfortunately, I can't check right now - I'm away from my Windows test box. With any luck, one of the PyCon sprinters tomorrow will have a Window box I can use as a point of reference.

**Comment by rmartin16** [comment]
All right; sounds good.

> Are the spaces you've added here purely cosmetic, or needed to support the regex?

My goal is to have standard prompts for each supported platform....while the regex is a bit more forgiving with whitespace so the copy button doesn't completely fail if someone gets the whitespace wrong....since I don't think there's a way to enforce semantics for the prompt.

Nonetheless, if we're going the regex route, I'll break up the regex a bit so its easier to maintain and understand as well as ensure uniformity of prompts within the docs. I can then roll this out to the other repos.

Also, as for Windows commands, I think I'm leaning towards defaulting to only showing `cmd` format when the command will also run on PowerShell; however, if the PowerShell command is different, then a separate tab would be added. Mostly taking a stance as a position to debate from; definitely open to a different policy.

**Review by freakboy3742 — APPROVED** [review]
This looks really solid; and I've confirmed the windows spacing with a user at the sprints who has a windows laptop.

**Pull request merged**
