### PR TITLE
Update linux docs in tutorial

### PR DESCRIPTION
**Pull request by sckarlin**
This change strengthens the admonition to use system Python under Linux and
gives an explanation of what happens when `briefcase create` fails when not
using system Python.

Folks new to BeeWare and working through the tutorial may not understand the
importance of using system Python.

This PR does not relate to an existing issue.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x ] I have read the **CONTRIBUTING.md** file
- [x ] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
Related issue:
- https://github.com/beeware/briefcase/issues/1329

Mostly as a note to myself (since I'll probably need to update quite a bit of docs), this need to re-run `briefcase create` will _hopefully_ go away once https://github.com/beeware/briefcase/pull/1714 is merged.

**Review by freakboy3742 — APPROVED** [review]
Thanks for the patch!

**Comment by sckarlin** [comment]
Thanks for including this.  As a power user on Linux (compiling Python from source), but new to BeeWare, I was tripped up with the term "Alternate Python Distributions" and simply skipped that section.  After all, I didn't feel I had a Python distribution of any kind.  I had an install.  So, the section didn't apply.  When it was explained to me that BeeWare could only use "system Python" -- that is, the Python officially installed as part of my Linux distribution, I understood.  This patch is to not bury the lede and let Linux folks know as early as possible that they need to use system Python.

**Comment by freakboy3742** [comment]
If you're still at the PyCon US sprints, don't forget to claim your challenge coin!

**Pull request merged**
