### PR TITLE
Develop a list of fundable projects

### PR DESCRIPTION
**Pull request by freakboy3742**
The [PSF Project Funding Working Group](https://github.com/psf/project-funding-wg) recently put out a call for funding proposals. This is a list of candidate BeeWare projects that could be funded.

The document is viewable in it's entirety [at this link](https://github.com/freakboy3742/beeware/blob/fundable-projects/FUNDABLE_PROJECTS.md)

This PR is not intended for merging; it exists purely as a way to gather feedback on a document within the Github ecosystem.

### CODE REVIEW

**Comment by phildini** [comment]
Here's my meta-comment: I think the time is right to do a voluntary "BeeWare Census", by which I mean, poll the widest community we can, see which BeeWare projects are getting the most use or have the most potential use, and then use that to guide what we put forward for funding.

A proposal that says "Here's a hundred projects already using briefcase, or rubicon, here's what we want to do next" is stronger because of the social proof.

**Comment by phildini** [comment]
Quick cases in point from searching:

- there's at least 60 repos on github using briefcase:
  - https://github.com/search?q=briefcase+filename%3Asetup.py&type=Code
  - https://github.com/search?q=briefcase+filename%3Arequirements.txt&type=Code
- there's at least 200 repos on github using toga:
  - https://github.com/search?q=toga+filename%3Arequirements.txt&type=Code
  - https://github.com/search?q=toga+filename%3Asetup.py&type=Code

Each of those repos is a customer, in some way, and they make BeeWare's funding case stronger. 

So.. what do they want us to improve?

**Comment by freakboy3742** [comment]
There's a lot of demo/test projects in those searches, and the "briefcase" search seems to be picking up a lot of noise - but agreed that surveying existing users would be worthwhile. 

The one thing that concerns me about using existing users as a driver for future development is that it is a self-selecting sample. For example - Briefcase doesn't currently have any support for Raspberry Pi. That means there won't be any repos out there for Raspberry Pi projects using Briefcase. That doesn't mean there isn't any interest in Raspberry Pi as a platform, though. There won't be any projects out there using toga-Android, either - but there's a *whole* lot of interest.

Polling the ~1000 people on the mailing list and the paid members might give a little breadth beyond that. We could even throw it out on Twitter for a general opinion, with a qualifying question that asks about current usage.

I'll put together a first-pass set of questions for feedback.

**Comment by xmunoz** [comment]
And customer feedback yet?

**Comment by freakboy3742** [comment]
@xmunoz We haven't had a chance to put the survey into the field; we're working on that.

I will note that the requests we are receiving on our support channels at present fall into two groups:

 * "How do I use Briefcase to package my PySide app on Android?" This is outside our control, because *PySide* doesn't support Android.

 * "How do I use numpy/scipy/etc on Android?" This is effectively the "Binary Wheels on mobile platforms" fundable piece of work.

**Comment by freakboy3742** [comment]
Given that BeeWare is now being effectively funded by Anaconda, I'm going to close this issue.

**Pull request closed without merging**
